"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Guest = { id: number; name: string; email: string; date: string; guests: number; rsvp: "Pending" | "Attending" | "Declined"; invited: boolean };
const dates = ["Friday, October 16 · 6:00 PM", "Sunday, October 18 · 10:00 AM"];
const initialGuests: Guest[] = [{ id: 1, name: "Priya Raman", email: "priya@example.com", date: dates[0], guests: 2, rsvp: "Pending", invited: false }];

export function GuestAdmin() {
  const [guests, setGuests] = useState<Guest[]>(initialGuests); const [message, setMessage] = useState(""); const [sending, setSending] = useState<number | null>(null);
  useEffect(() => { const saved = localStorage.getItem("golu-admin-guests"); if (saved) setGuests(JSON.parse(saved)); }, []); useEffect(() => { localStorage.setItem("golu-admin-guests", JSON.stringify(guests)); }, [guests]);
  const attending = guests.filter((guest) => guest.rsvp === "Attending").reduce((count, guest) => count + guest.guests, 0);
  function addGuest(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setGuests((current) => [...current, { id: Date.now(), name: String(data.get("name")), email: String(data.get("email")), date: String(data.get("date")), guests: 1, rsvp: "Pending", invited: false }]); event.currentTarget.reset(); }
  async function sendInvite(guest: Guest) { setSending(guest.id); setMessage(""); const response = await fetch("/api/invitations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(guest) }); const result = await response.json() as { error?: string }; if (response.ok) { setGuests((current) => current.map((item) => item.id === guest.id ? { ...item, invited: true } : item)); setMessage(`Invitation sent to ${guest.name}.`); } else setMessage(result.error ?? "Unable to send invitation."); setSending(null); }
  return <main className="admin-page"><header className="admin-header"><Link href="/">← Back to site</Link><span>GOLU HOST DESK</span></header><section className="admin-intro"><p className="eyebrow">PRIVATE HOST TOOLS</p><h1>Guest list &<br /><em>invitations.</em></h1><p>Track RSVP responses and send a personalised invitation to every guest.</p></section><section className="admin-stats"><div><span>Guest records</span><strong>{guests.length}</strong></div><div><span>Confirmed people</span><strong>{attending}</strong></div><div><span>Invitations sent</span><strong>{guests.filter((guest) => guest.invited).length}</strong></div></section><section className="admin-content"><form className="guest-form" onSubmit={addGuest}><p className="eyebrow">ADD A GUEST</p><label>Name<input required name="name" placeholder="Guest name" /></label><label>Email<input required name="email" type="email" placeholder="guest@email.com" /></label><label>Preferred day<select name="date">{dates.map((date) => <option key={date}>{date}</option>)}</select></label><button className="button">Add to guest list <span>→</span></button></form><div className="guest-list"><div className="list-heading"><div><p className="eyebrow">GUEST LIST</p><h2>Everyone invited</h2></div><span>{guests.length} guests</span></div>{message && <p className="admin-message">{message}</p>}<div className="guest-table">{guests.map((guest) => <article key={guest.id}><div><strong>{guest.name}</strong><span>{guest.email}</span></div><div><span>{guest.date}</span><b className={guest.rsvp.toLowerCase()}>{guest.rsvp}</b></div><button disabled={sending === guest.id} onClick={() => sendInvite(guest)}>{sending === guest.id ? "Sending…" : guest.invited ? "Send again" : "Send invite"} ↗</button></article>)}</div></div></section><p className="admin-note">Invitation delivery is powered by Resend. Add <code>RESEND_API_KEY</code>, <code>INVITE_FROM_EMAIL</code>, and <code>NEXT_PUBLIC_SITE_URL</code> in Vercel before sending live email.</p></main>;
}
