import { SiteFooter } from "../components/site-footer";
import { SiteHeader } from "../components/site-header";

export default function About() {
  return <main>
    <section className="about-hero page-hero"><SiteHeader active="/about" /><div className="page-title"><p className="eyebrow">ABOUT THE FESTIVAL</p><h1>Nine sacred<br /><em>nights.</em></h1><p>A time for Devi, for music and stories, and for opening our homes to the people around us.</p></div><div className="sunburst">✦</div></section>
    <section className="about-story"><div className="about-emblem" aria-hidden="true"><span>❀</span><b>🪔</b><span>❀</span></div><article><p className="eyebrow">NAVRATRI</p><h2>A celebration of<br />good over evil.</h2><p>Navratri—the nine sacred nights—is one of India&apos;s most celebrated festivals. It begins on Pradhamai, the first day after Amavasya in the Tamil month of Purattasi.</p><p>These nine days honour Devi and commemorate the victory of good over evil: the end of the atrocities of Asuras including Mahishasuran, Shumban, Nishumban, Madhukaidapan, Thumralochanan, and Rakthabheejan.</p></article></section>
    <section className="devi-days"><p className="eyebrow">THE NINE DAYS OF DEVI</p><div><article><b>Days 1–3</b><h3>Sri Durga</h3><p>Worshipped for courage, protection, and the strength to overcome.</p></article><article><b>Days 4–6</b><h3>Sri Lakshmi</h3><p>Worshipped for abundance, wellbeing, and generosity.</p></article><article><b>Days 7–9</b><h3>Sri Saraswati</h3><p>Worshipped for knowledge, music, learning, and creativity.</p></article></div></section>
    <section className="about-story about-story-reverse"><article><p className="eyebrow">KOLU AT HOME</p><h2>Stories, songs,<br />and sundal.</h2><p>In South India, Navratri is also a time to invite friends, relatives, and neighbours into the home to see the Kolu. For all nine days, the house comes alive with songs, dances, conversation, and the stories told by each doll.</p><p>Special dishes are made every day, with a different sundal as a Navratri essential. Guests are served sundal and, when they leave, receive a little to take home along with traditional thamboolam.</p></article><div className="thamboolam" aria-label="Traditional thamboolam illustration"><span>🍃</span><b>◉</b><i>❀</i><em>THAMBOOLAM</em></div></section>
    <section className="album-callout"><p className="eyebrow">OUR MEMORIES</p><h2>See our Golu<br />through the years.</h2><p>Our family&apos;s photographs live in the shared album.</p><a className="button" href="https://photos.app.goo.gl/m3B7RaYJcruuyr8Y9" target="_blank" rel="noreferrer">Open the photo album <span>↗</span></a></section><SiteFooter />
  </main>;
}
